import { SlideData } from '../types';

export const MODULE_4_SLIDES: SlideData[] = [
  {
    id: 'slide_m4_1',
    number: 1,
    title: 'Module 4 Overview: Pushdown Automata (PDA)',
    category: '1. PDA Definition',
    textbookSection: 'Section 6.1',
    bullets: [
      'A Pushdown Automaton (PDA) is a finite automaton augmented with an INFINITE STACK memory (LIFO).',
      'Formal 7-Tuple Definition: M = (Q, Σ, Γ, δ, q0, Z0, F)',
      '  • Q: Finite set of states',
      '  • Σ: Input alphabet',
      '  • Γ: Stack alphabet',
      '  • δ: Transition function δ: Q × (Σ ∪ {ε}) × Γ → 𝒫(Q × Γ*)',
      '  • q0: Initial state (q0 ∈ Q)',
      '  • Z0: Initial stack symbol (Z0 ∈ Γ)',
      '  • F: Set of accepting / final states (F ⊆ Q)'
    ],
    formulas: [
      'δ(q, a, Z) = { (p, γ1), (r, γ2), ... }',
      'where a ∈ Σ ∪ {ε}, Z ∈ Γ is top of stack, and γ ∈ Γ* replaces Z.'
    ],
    exampleBox: {
      title: 'PDA Stack Operations Explained',
      description: 'Given transition δ(q, a, Z) = (p, γ):\n  • PUSH: γ = XZ (pushes X onto stack above Z)\n  • POP: γ = ε (removes Z from top of stack)\n  • NO-CHANGE: γ = Z (retains Z as top of stack)\n  • REPLACE: γ = Y (replaces top symbol Z with Y)'
    }
  },
  {
    id: 'slide_m4_2',
    number: 2,
    title: 'PDA Instantaneous Descriptions (ID) & Acceptance Modes',
    category: '2. ID & Acceptance',
    textbookSection: 'Section 6.2',
    bullets: [
      'Instantaneous Description (ID): Triplet (q, w, γ) representing current state q, remaining unread input string w, and current stack content γ (leftmost symbol = top of stack).',
      'Two Equivalent Acceptance Modes for PDAs:',
      '  1. Acceptance by Final State (L(M)): (q0, w, Z0) ⊢* (qf, ε, α) where qf ∈ F.',
      '  2. Acceptance by Empty Stack (N(M)): (q0, w, Z0) ⊢* (q, ε, ε) for any state q ∈ Q.',
      'Theorem: A language L is accepted by some PDA by final state IF AND ONLY IF L is accepted by some PDA by empty stack.'
    ],
    exampleBox: {
      title: 'ID Step Transition Trace Example for L = {0^n 1^n | n ≥ 1}',
      description: 'Input string w = "0011":\n  (q0, 0011, Z0)   ⊢ (q0, 011, 0Z0)     [Push 0]\n                   ⊢ (q0, 11, 00Z0)     [Push 0]\n                   ⊢ (q1, 1, 0Z0)       [Pop 0 on input 1]\n                   ⊢ (q1, ε, Z0)        [Pop 0 on input 1]\n                   ⊢ (qf, ε, Z0)        [Accept on ε, Z0 -> Final state!]'
    }
  },
  {
    id: 'slide_m4_3',
    number: 3,
    title: 'Equivalence of CFG and Pushdown Automata',
    category: '3. CFG <-> PDA',
    textbookSection: 'Section 6.3',
    bullets: [
      'Fundamental Equivalence Theorem: A language L is Context-Free (generated by a CFG) IF AND ONLY IF L is accepted by a Pushdown Automaton.',
      'Converting CFG G = (V, T, P, S) to 1-State PDA M = ({q}, T, V ∪ T, δ, q, S, ∅) accepting by empty stack:',
      '  1. For every variable production A → α ∈ P: Add transition δ(q, ε, A) = (q, α).',
      '  2. For every terminal a ∈ T: Add matching pop transition δ(q, a, a) = (q, ε).',
      'This top-down PDA simulates leftmost derivations directly on the stack!'
    ],
    exampleBox: {
      title: 'CFG to PDA Rule Example',
      description: 'CFG Rule: S → a S b | ε\nConverted PDA Transitions:\n  • δ(q, ε, S) = { (q, aSb), (q, ε) }\n  • δ(q, a, a) = { (q, ε) }\n  • δ(q, b, b) = { (q, ε) }'
    }
  },
  {
    id: 'slide_m4_4',
    number: 4,
    title: 'Deterministic Pushdown Automata (DPDA)',
    category: '4. DPDA vs NPDA',
    textbookSection: 'Section 6.4',
    bullets: [
      'A Deterministic PDA (DPDA) has at most one choice in any situation.',
      'Conditions for Determinism:',
      '  1. For any q ∈ Q, a ∈ Σ ∪ {ε}, and Z ∈ Γ: |δ(q, a, Z)| ≤ 1.',
      '  2. If δ(q, ε, Z) is non-empty, then δ(q, a, Z) MUST be empty for ALL a ∈ Σ.',
      'Crucial Contrast with Finite Automata:',
      '  • For Finite Automata: DFA and NFA have EQUIVALENT power (both recognize regular languages).',
      '  • For Pushdown Automata: DPDA is STRICTLY LESS POWERFUL than NPDA! (DPDAs cannot recognize inherent ambiguous/palindromic languages like L = {w w^R}).'
    ],
    exampleBox: {
      title: 'Power Hierarchy Comparison',
      description: '• Regular Languages ⊂ Deterministic CFLs (DPDA) ⊂ Context-Free Languages (NPDA)\n• Example non-DPDA CFL: L = {w w^R | w ∈ {a,b}*} (requires guessing midpoint -> non-deterministic!).'
    }
  }
];
